### ISSUE TITLE
프로젝트 시작 전 조사

### ISSUE THREAD

**Issue by eddie94** [VisionGYM/Fake-Face-Detector#1]
# 개요

본 프로젝트의 목적은
```
GAN으로 생성된 얼굴과 실제 사람의 얼굴을 분류하는것
```
을 목적으로 한다

이를 달성하기 위해 필요한 전제조건을 아래에 기술한다

- 사용할 데이터셋
- 사용할 GAN모델
- 분류기 학습을 위해 사용되는 데이터 처리 및 학습 방법

# 관련 이슈

해당 이슈에 관련된 이슈나 PR을 태그

# 완료 조건

해당 이슈를 달성하기 위한 조건을 기술

- [x] 사용할 데이터셋을 정한다
- [x] 최종적으로 사용할 GAN모델을 정한다
- [x] 얼굴 인식을 위해 사용할 데이터 처리 방식을 결정
- [x] 역할분담
- [x] 향후 과제가 될 수 있는 포인트 논의

**Comment by rlacodls3109** [comment]
GAN
가짜이미지를 만들어내도록 학습되는 생성자와, 가짜와 진짜 이미지를 구별하는 감별자를 경쟁시켜 학습하면 생성자가 점점 진짜와 같은 이미지를 만들어내게 되는 원리
https://devocean.sk.com/blog/techBoardDetail.do?ID=163330

딥페이크 탐지에 걸림돌이 되는 3가지 문제
학습되지 않은 생성 기법에 대한 성능저하
Adversarial Attack에 대한 모델의 취약성
비디오 압축, 빛의 노출 등 물리적 변화에 의한 성능저하

GAN 데이터셋
CelebA
앞서 언급한 대표적인 데이터셋 중 하나로, 유명인들의 얼굴 이미지를 수백만 장 제공합니다. 각 이미지에는 다양한 표정, 각도 및 배경이 포함되어 있음
https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

VGGFace2: 비전그래프(VGG)에서 수집한 대규모 인물 얼굴 이미지 데이터셋으로, 수천명의 유명인들의 얼굴 이미지를 포함하고 있습니다.
https://www.robots.ox.ac.uk/~vgg/software/vgg_face/

IMDB-WIKI Dataset: 인터넷 영화 데이터베이스(IMDB)와 위키미디어(Wikipedia)에서 수집된 인물의 얼굴 이미지 데이터셋으로, 다양한 나이, 인종 및 성별의 인물들을 포함하고 있습니다.
https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/

GAN 모델
StyleGAN L인물 사진의 특징을 더 세밀하게 조절하고, 생성된 이미지와 실제 이미지 간의 차이를 더 정확하게 분류
https://keras.io/examples/generative/stylegan/

**Comment by eddie94** [comment]
데이터셋 : celeba
사용할 GAN 모델: 바닐라 GAN
GAN: @rlacodls3109 @dodododok 
분류기 : @sewoong02 
데이터로더 : @rudalsss 
데이터 처리 방식: 추후 논의
