### ISSUE TITLE
분류기 캐치업

### ISSUE THREAD

**Issue by eddie94** [VisionGYM/Fake-Face-Detector#3]
# 개요

본격적으로 프로젝트를 진행하기 전에 분류기를 파이토치로 작성

# 관련 이슈

해당 이슈에 관련된 이슈나 PR을 태그

# 완료 조건

- [ ] 이미지 분류기(ResNet)를 파이토치로 작성
- [ ] 모델의 학습을 colab상으로 확인
- [ ] 코드 링크를 공유

**Comment by sewoong02** [comment]
https://colab.research.google.com/drive/1Tpi2nlzhplQ5Y5MB-JZjLQqjlBpl57Ag#scrollTo=Waree-xfEiTe

선배님 유튜브를 참고해서 이미지 분류기(ResNet)을 파이토치로 작성하였고 공부했습니다.
colab의 gpu로는 너무 느려서 주피터 노트북에서 제 gpu로 실행했고 성능을 확인했습니다.



![Image](https://github.com/VisionGYM/Fake-Face-Detector/assets/89050956/da91c5cc-7449-4198-9751-54faeedd574e)


다만 실제 데이터를 사용해서 학습하는건 아직 모르겠어서 추가적으로 더 공부해오겠습니다.

**Comment by eddie94** [comment]
@sewoong02 
파이토치로 학습이 되는걸 확인하셨으면 파이토치 라이트닝으로도 똑같이 학습해 보세요

**Comment by sewoong02** [comment]
https://colab.research.google.com/drive/1v7aYC3qFRSYuaro9vapIqZkcGpKKs5uf#scrollTo=Fnjt8yt0sBA1

basic block을 없애보려고 했는데 코드가 난잡해지는거 같아서 기존 형식을 거의 유지하면서 코드를 파이토치 라이트닝으로 수정하였습니다. 주피터 노트북에서 커널이 계속 죽는 문제가 생겼고 메모리 문제로 추측되지만 정확한 원인을 파악하지 못했습니다. 일단 학습과정을 확인하는 코드를 제거하니 학습이 완료됨을 확인했습니다.

![스크린샷 2024-05-30 174413](https://github.com/VisionGYM/Fake-Face-Detector/assets/89050956/33f05159-a636-4567-ae3d-c9832f3a41e3)

**Comment by sewoong02** [comment]
코드 접근허용했습니다
https://colab.research.google.com/drive/1v7aYC3qFRSYuaro9vapIqZkcGpKKs5uf#scrollTo=Fnjt8yt0sBA1

**Comment by eddie94** [comment]
@sewoong02 
코드 푸시 하시고 풀리퀘 올려주세요
리뷰할때 수정사항 알려드리겠습니다

**Comment by sewoong02** [comment]
branch만들고 commit하고 pull request 완료하였습니다.
